//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr14V
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketId { get; set; }
        public int ScreeningId { get; set; }
        public int UserId { get; set; }
        public int SeatNumber { get; set; }
        public Nullable<System.DateTime> PurchasedAt { get; set; }
    
        public virtual Screenings Screenings { get; set; }
        public virtual Users Users { get; set; }
    }
}
